name: "🔎 Diagnose OIDC Permissions"

on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI (OIDC)
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JFROG_URL }}
          JF_PROJECT: ${{ vars.PROJECT_KEY }}
        with:
          version: latest
          oidc-provider-name: github-bookverse-inventory
          oidc-audience: jfrog-github
      - name: Show JFrog user and repo
        run: |
          set -e
          jf c show || true
          echo "--- whoami ---"
          jf rt curl -XGET "/api/security/user" || true
          echo "--- repo info ---"
          jf rt curl -XGET "/api/repositories/${{ vars.PROJECT_KEY }}-build-info" || true
      - name: Test write to build-info repo
        run: |
          set -e
          echo "hello" > test-oidc.txt
          if jf rt u test-oidc.txt "${{ vars.PROJECT_KEY }}-build-info/test-oidc.txt" --project "${{ vars.PROJECT_KEY }}"; then
            echo "✅ Upload succeeded"
            jf rt del --quiet "${{ vars.PROJECT_KEY }}-build-info/test-oidc.txt" --project "${{ vars.PROJECT_KEY }}" || true
          else
            echo "❌ Upload failed"
            exit 1
          fi
