name: Test Manual Promotion

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Application version to test promotion (e.g., 5.32.90)'
        required: false
        default: '5.32.90'
        type: string

jobs:
  test-manual-promotion:
    name: "Test Manual Promotion via Direct API"
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: "[Setup] Checkout"
        uses: actions/checkout@v4

      - name: "[Setup] JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest
          oidc-provider-name: bookverse-inventory-github
          oidc-audience: ${{ vars.JFROG_URL }}
          disable-job-summary: true
          disable-auto-build-publish: true

      - name: "[Test] Manual Promotion"
        env:
          PROVIDER_NAME: bookverse-inventory-github
        run: |
          echo "🧪 Testing manual promotion for version: ${{ inputs.app_version }}"
          ./test-manual-promotion.sh "${{ inputs.app_version }}"
